### product API requests
### read all products
GET http://localhost:3001/product-api/products

### create a new product
POST http://localhost:3001/product-api/products
Content-Type: application/json

{
    "productId":104,
    "name":"shirt",
    "price":2000,
    "brand":"Nike"
}

### update a product
PUT http://localhost:3001/product-api/products
Content-Type: application/json

{
    "productId":104,
    "name":"pant",
    "price":3500,
    "brand":"Nike"
}

### get product by id 
GET http://localhost:3001/product-api/product-id/104

### get product by brand
GET http://localhost:3001/product-api/product-brand/nike

### delete product by id
DELETE http://localhost:3001/product-api/products/104



###  user API requests
### read all users
GET http://localhost:3001/user-api/users

### create new user
POST http://localhost:3001/user-api/users
Content-Type: application/json

{
    "id": 4,
    "name": "Ram",
    "city": "Banglore"
}

### update a user by id
PUT http://localhost:3001/user-api/users
Content-Type: application/json

{
    "id": 4,
    "name": "Mahesh",
    "city": "Hyderabad"
}

### get user by id
GET http://localhost:3001/user-api/users/4

### delete user by id
DELETE http://localhost:3001/user-api/users/4
